### ISSUE TITLE
Security issue: Port should not be open 

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/pleroma_ynh#1]
Hi
If someone maintains this app in future, there is security issue as the port on which the Pleroma listens is opened while installation. This is not required and maybe a security issue.

**Comment by yalh76** [comment]
Port opening fixed in https://github.com/YunoHost-Apps/pleroma_ynh/commit/4d1526713c0f9f0d8e33bb3a0d8ce4d1712465a1
