### ISSUE TITLE
change_url

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/pleroma_ynh#10]
I just tested the change_url option... wokes  somehow - login does not work anymore
and all avatars are gone

**Comment by rocky-III** [comment]
In my understanding change_url can´t really work with pleroma - because with the url you also change the adress of every rigisted user on the pleroma server...

**Comment by yalh76** [comment]
Hi @rocky-III, 

Just tested, the change_url and it's working, able to still able to login with mastodon or pleroma
