### ISSUE TITLE
Where is the configuration file

### ISSUE THREAD

**Issue by fur2** [YunoHost-Apps/pleroma_ynh#101]
How do I modify Pleroma's settings? I'm trying to find a configuration file.
Is this different from installing Pleroma directly?😥

**Comment by yalh76** [comment]
What version of pleroma are you using ?
What settings do you want to change ?

**Comment by fur2** [comment]
V 1.1.7
I tried changing the mail settings so that Pleroma could send mail using Sendgrid. And change the background image. I can't find Pleroma's profile in Yuno.

**Comment by yalh76** [comment]
Config file is in /etc/pleroma since 1.1.7

**Comment by fur2** [comment]
thx 😘
