### ISSUE TITLE
Transfering the config to/from the database

### ISSUE THREAD

**Issue by volfclub** [YunoHost-Apps/pleroma_ynh#109]
https://docs-develop.pleroma.social/backend/administration/CLI_tasks/config/
Should the profile enable this by default? To support the new features of 2.0?

**Comment by yalh76** [comment]
What are the benefits to have the configuration in the database ?

**Comment by volfclub** [comment]
https://pleroma.social/blog/2020/03/08/releasing-pleroma-2-0-0/

> **Admin Improvements**  Many Pleroma users ask the question: Why do I have to edit configuration files to manage my instance? Well, that won't be an issue anymore from 2.0.0 on.
Our Admin frontend received a lot of love for this release. We now support storing your configuration in the database, so that you should be able to manage your instance without having to edit configuration files. This is the first release in which we support this method of running your instance, so there might still be some rough edges. Please read the documentation before using it!

Visual management settings are easier and more compatible with out-of-the-box, and perhaps also essential for modern products.

**Comment by elenners** [comment]
I am trying to do this right now. I used Yunohost because I know next to nothing about using console commands, so I am struggling a bit with this. I edited /etc/pleroma/config.exs to add config :pleroma, configurable_from_database: true as stated in the guide above. 

I cannot get ./bin/pleroma_ctl config migrate_to_db to do anything. Every time I refresh the admin UI I still get the "Request failed with status code 400 - To use this endpoint you need to enable configuration from database." Can you provide the exact way to enter it in the console to get it to take? I need to be able to do the admin stuff from the front end UI since I have no idea how to in the console. Thank you for any help you can give.

**Comment by gnouts** [comment]
I had the same problem and it was frustrating to view this admin web page, greyed out, without the possible to edit it ^^
I tried the same command as @elenners , from the documentation but I couldn't get it to work neither.

**I managed to make it work by changing the last line in `/etc/pleroma/config.exs`** and edit from this : 
```
config :pleroma, configurable_from_database: false
```
to this : 
```
config :pleroma, configurable_from_database: true
```
Then restarting pleroma did the trick (`sudo systemctl restart pleroma`) :wink: 

I also think this should be the default :slightly_smiling_face:

**Comment by elenners** [comment]
> I had the same problem and it was frustrating to view this admin web page, greyed out, without the possible to edit it ^^
> I tried the same command as @elenners , from the documentation but I couldn't get it to work neither.
> 
> **I managed to make it work by changing the last line in `/etc/pleroma/config.exs`** and edit from this :
> 
> ```
> config :pleroma, configurable_from_database: false
> ```
> 
> to this :
> 
> ```
> config :pleroma, configurable_from_database: true
> ```
> 
> Then restarting pleroma did the trick (`sudo systemctl restart pleroma`) 😉
> Correct me if I'm wrong, but I think this change will be wiped at the next update, right ?
> 
> I also think this should be the default 🙂

You are the best!! I didn't realize that the stupid entry was already in there so I had added it and didn't realize it was listed as false further down. Thank you 😁

**Comment by yalh76** [comment]
Maybe you should do a PR to let all guys disfrute of that....

**Comment by yalh76** [comment]
still looking for a maintainer/co-maintainer ;)
As I don't user pleroma_ynh/pleroma
