### ISSUE TITLE
Unable to upload file

### ISSUE THREAD

**Issue by hieronymousch** [YunoHost-Apps/pleroma_ynh#110]
After selecting a file to upload, a short progress bar is shown but nothing happens and unable to post.
Behaviour both on web interface and with tusky. Happens with all browsers. 

Running 
Backend Version
1.1.9
Frontend Version
36910935

Nginx error log only complains about missing ynh_overlay.css, ynh_portal.js files but does this also on a normal page refresh.

Thanks for your help

**Comment by bendia-** [comment]
Same problem running
Backend Version
2.0.0
Frontend Version
38455294 

Here, the nginx access.log

`IP Addresss - - [13/Mar/2020:18:51:02 +0100] "PATCH /api/v1/accounts/update_credentials HTTP/2.0" 500 1335 "https://social.pansebete.net/user-settings" "USER_AGENT"`

**Comment by yalh76** [comment]
Just tested and yes there is an issue to upload files. I have to figure it out.

**Comment by xaloc33** [comment]
I think that the issue has to do with pleroma not being able to figure out where the /static and /uploads folders are.

**Comment by bendia-** [comment]
@xaloc33 

`config :pleroma, :instance, static_dir: "/home/yunohost.app/pleroma/static"
config :pleroma, Pleroma.Uploaders.Local, uploads: "/home/yunohost.app/pleroma/uploads"
`

These 2 lines in _/etc/pleroma/config.exs_ would have no effect?

**Comment by xaloc33** [comment]
@bendia- 

It doesn't seem like it does. Here I'll add the error when pleroma is started:
```
19:40:17.150 [error] Could not access the custom emoji directory /home/yunohost.app/pleroma/static/emoji: eacces
```

And here the error when you try to upload media:
```
Mar 19 19:43:32 xaloc pleroma[5197]: 19:43:32.966 request_id=Ff3IycprglGTV6n4AAjC [error] Internal server error: %File.CopyError{action: "copy", destination: "/home/yunohost.app/pleroma/uploads/9d1e1233356e545415c7f97391591e155e90fc797ab596672ad6dc00da0d3b40.jpg", on: "", reason: :eacces, source: "/tmp/plug-1584/multipart-1584643412-595847540372065-1"}
Mar 19 19:43:32 xaloc pleroma[5197]: 19:43:32.977 [error] #PID<0.6901.0> running Pleroma.Web.Endpoint (connection #PID<0.6900.0>, stream id 1) terminated
Mar 19 19:43:32 xaloc pleroma[5197]: Server: fedi.xaloc.space:80 (http)
Mar 19 19:43:32 xaloc pleroma[5197]: Request: POST /api/v1/media
Mar 19 19:43:32 xaloc pleroma[5197]: ** (exit) an exception was raised:
Mar 19 19:43:32 xaloc pleroma[5197]:     ** (File.CopyError) could not copy from "/tmp/plug-1584/multipart-1584643412-595847540372065-1" to "/home/yunohost.app/pleroma/uploads/9d1e1233356e545415c7f97391591e155e90fc797ab596672ad6dc00da0d3b40.jpg": permission denied
Mar 19 19:43:32 xaloc pleroma[5197]:         (elixir) lib/file.ex:814: File.cp!/3
Mar 19 19:43:32 xaloc pleroma[5197]:         (pleroma) lib/pleroma/uploaders/local.ex:27: Pleroma.Uploaders.Local.put_file/1
Mar 19 19:43:32 xaloc pleroma[5197]:         (pleroma) lib/pleroma/uploaders/uploader.ex:48: Pleroma.Uploaders.Uploader.put_file/2
Mar 19 19:43:32 xaloc pleroma[5197]:         (pleroma) lib/pleroma/upload.ex:65: Pleroma.Upload.store/2
Mar 19 19:43:32 xaloc pleroma[5197]:         (pleroma) lib/pleroma/web/activity_pub/activity_pub.ex:971: Pleroma.Web.ActivityPub.ActivityPub.upload/2
Mar 19 19:43:32 xaloc pleroma[5197]:         (pleroma) lib/pleroma/web/mastodon_api/controllers/mastodon_api_controller.ex:815: Pleroma.Web.MastodonAPI.MastodonAPIController.upload/2
Mar 19 19:43:32 xaloc pleroma[5197]:         (pleroma) lib/pleroma/web/mastodon_api/controllers/mastodon_api_controller.ex:5: Pleroma.Web.MastodonAPI.MastodonAPIController.action/2
Mar 19 19:43:32 xaloc pleroma[5197]:         (pleroma) lib/pleroma/web/mastodon_api/controllers/mastodon_api_controller.ex:5: Pleroma.Web.MastodonAPI.MastodonAPIController.phoenix_controller_pipeline/2
```

If it is of any help

**Comment by yalh76** [comment]
@xaloc33 it's wahat i've seen. but even giving full rights to anybody on /home/yunohost.app/pleroma/uploads, there is still the same error...

maybe it comes from `/tmp/plug-1584/multipart-1584643412-595847540372065-1` but I don't know how to make a diagnosis of that...

**Comment by xaloc33** [comment]
I tried a bunch of things and by changing the static directory in the config file to something like `instance/../../../../../home/yunohost.app/pleroma/static` the custom emoji problem seemed to disappear but I'm not sure if the static directory was actually working. I tried similar stuff for the uploads directory none of which worked. I think it is an issue of where pleroma thinks that the folder is and where it actually is.



> maybe it comes from `/tmp/plug-1584/multipart-1584643412-595847540372065-1` but I don't know how to make a diagnosis of that...

Might be I'll try to open an issue to pleroma support and see if they can help.

**Comment by xaloc33** [comment]
I don't know why but using the folder that there already exists at `/var/www/pleroma/instance/static` for the static dir and `/var/www/plerom/instance/uploads` it works. I don't know why it does not work when changed to `/home/yunohost.app/pleroma/static`

**Comment by bendia-** [comment]
Related to [this issue](https://git.pleroma.social/pleroma/pleroma/issues/1289) opened on pleroma gitlab by @yalh76 ?

**Comment by noccio** [comment]
I reported this thread as a workaround in yunohost forum https://forum.yunohost.org/t/pleroma-unable-to-send-images/10455

**Comment by strikersh** [comment]
So after tinkering arround I found another way to fix the issue (might not be recommended change the `ProtectedHome=True` to `False` in the systemd service configuration)

**Comment by nr458h** [comment]
Hi all,
I am on pleroma 2.0.7 and the error occurred to me too.
From the issue itself it is unclear if I should adapt one of the workarounds or if this is unattended behavior?

Thanks for help in advance
