### ISSUE TITLE
Yunohost nginx diagnose 

### ISSUE THREAD

**Issue by hieronymousch** [YunoHost-Apps/pleroma_ynh#123]
Hi,

I applied the recommended changes from the yunohost nginx config check (after messages in diagnose) by using yunohost tools regen-conf nginx --force.

This "corrected" the files but breaks Pleroma login. I have to comment the SSO line in nginx conf to be able to login.

Pleroma complains with these lines:

2020/05/25 12:56:40 [error] 25081#25081: *1791 lua entry thread aborted: runtime error: /usr/share/ssowat/access.lua:360: string argument only
stack traceback:
coroutine 0:
        [C]: in function 'decode_base64'
        /usr/share/ssowat/access.lua:360: in function </usr/share/ssowat/access.lua:1>, client: XX.57.170, server: XXXX.xyz, request: "GET /api/v1/notifications?limit=80&since_id=85 HTTP/1.1", host: "XXX.xyz

**Comment by yalh76** [comment]
did you installed your pleroma instance as a private instance ?

**Comment by hieronymousch** [comment]
I believe that I did... It's been a couple of months. The Groups & Permissions page shows pleroma only allowed for users (no anonymous)

**Comment by yalh76** [comment]
maybe it's the issue, it's better to make the app public and connect to pleroma with YunoHost lougout

**Comment by hieronymousch** [comment]
I'll do that but can you give a pointer on who to do that?
