### ISSUE TITLE
The installer crashes when a password with special characters is used

### ISSUE THREAD

**Issue by OniriCorpe** [YunoHost-Apps/pleroma_ynh#132]
**Describe the bug**
Installation crash

**Versions**
- Hardware: Proxmox VM (RAM : 2GB ; CPU : 2 cores)
- YunoHost version: 4.0.3
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: French locale
- Using, or trying to install package version/branch: official master package (via `yunohost app install pleroma --label Pleroma`)

**To Reproduce**
*Steps to reproduce the behavior.*
`# yunohost app install pleroma --label Pleroma`

**Expected behavior**
Pleroma installed

**Logs**
https://paste.yunohost.org/raw/jejogaripu

**Comment by OniriCorpe** [comment]
Fixed using a password without special characters.

The password which cause the crash: `^S%iyw*NT65^*6j%82Fo$&GL`

**Comment by raphaeljolivet** [comment]
Same here.
Using ';' in a password ...
