### ISSUE TITLE
Public/new user registration?

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/pleroma_ynh#133]
Hello,

I wanted to install Pleroma now that LDAP is working but I don't understand what are the meaning of
                    "en": "Is it a public application?",
and
                    "en": "Is the registration open for new users?",

I want to install a pleroma instance that can communicate with other instances and been seen by others...
Should I check or not the question "Is it a public application?"

I want all users of my yunohost (present and future) to be able to get a pleroma account thanks to LDAP. However, I don't want people to be able to register an account through pleroma. New users can only be created by me when I create a new account in Yunohost.
Should I check or not the question "Is the registration open for new users?" ?

**Comment by yalh76** [comment]
> 
> 
> Hello,
> 
> I wanted to install Pleroma now that LDAP is working but I don't understand what are the meaning of
> "en": "Is it a public application?",
> and
> "en": "Is the registration open for new users?",
> 
> I want to install a pleroma instance that can communicate with other instances and been seen by others...
> Should I check or not the question "Is it a public application?"
You have to say yes to "Is it a public application?"

> 
> I want all users of my yunohost (present and future) to be able to get a pleroma account thanks to LDAP. However, I don't want people to be able to register an account through pleroma. New users can only be created by me when I create a new account in Yunohost.
> Should I check or not the question "Is the registration open for new users?" ?
You have to say no to "Is the registration open for new users?"
