### ISSUE TITLE
Pleroma dropped support for Ostatus, description should be updated

### ISSUE THREAD

**Issue by MCMic** [YunoHost-Apps/pleroma_ynh#138]
Since 2.0 Pleroma does not support Ostatus anymore, so the description should be uptated to mention Activity Pub instead of Ostatus.

https://pleroma.social/blog/2020/03/08/releasing-pleroma-2-0-0/

**Comment by MCMic** [comment]
The description of the github repo is still mentionning OStatus.

**Comment by yalh76** [comment]
Description updated
