### ISSUE TITLE
Installer crashed 

### ISSUE THREAD

**Issue by raphaeljolivet** [YunoHost-Apps/pleroma_ynh#144]
I have a brand new installation of Yunohost 4.0.8.
The installation of pleroma failed.
I suspected the usage of special characters in the password (like previously reported) but it fails with a alphanumeric password too.

Here is the full trace : 

> 2020-11-04 10:45:24,281: DEBUG - + ynh_app_setting set pleroma checksum__etc_systemd_system_pleroma.service 05d127b61c1f9283b7c9f612a009d64c
> 2020-11-04 10:45:24,283: DEBUG - + [[ set == \d\e\l\e\t\e ]]
> 2020-11-04 10:45:24,283: DEBUG - + ACTION=set
> 2020-11-04 10:45:24,284: DEBUG - + APP=pleroma
> 2020-11-04 10:45:24,285: DEBUG - + KEY=checksum__etc_systemd_system_pleroma.service
> 2020-11-04 10:45:24,286: DEBUG - + VALUE=05d127b61c1f9283b7c9f612a009d64c
> 2020-11-04 10:45:24,287: DEBUG - + python2.7 -
> 2020-11-04 10:45:24,688: DEBUG - + [[ checksum__etc_systemd_system_pleroma.service =~ ^(unprotected|skipped)_ ]]
> 2020-11-04 10:45:24,690: DEBUG - + '[' -n '' ']'
> 2020-11-04 10:45:24,691: DEBUG - + unset backup_file_checksum
> 2020-11-04 10:45:24,692: DEBUG - + chown root: /etc/systemd/system/pleroma.service
> 2020-11-04 10:45:24,693: DEBUG - + systemctl enable pleroma --quiet
> 2020-11-04 10:45:25,496: DEBUG - + systemctl daemon-reload
> 2020-11-04 10:45:26,504: INFO - [############+.......] > Making setup...
> 2020-11-04 10:45:26,507: DEBUG - + echo '[############+.......] > Making setup...'
> 2020-11-04 10:45:26,510: DEBUG - + chown -R pleroma:pleroma /var/www/pleroma
> 2020-11-04 10:45:26,611: DEBUG - + pushd /var/www/pleroma/pleroma
> 2020-11-04 10:45:26,612: DEBUG - /var/www/pleroma/pleroma /var/cache/yunohost/from_file/pleroma_ynh-a71d71e2e87cc8c8acd6393bdcb38c9dc4e9ba21/scripts
> 2020-11-04 10:45:26,613: DEBUG - + su pleroma -s /bin/bash -lc '/var/www/pleroma/pleroma/bin/pleroma_ctl instance gen --force     --output /etc/pleroma/config.exs     --output-psql /tmp/setup_db.psql     --domain social.raphael-jolivet.name     --instance-name "Raph J "     --admin-email raph@cloud.raphael-jolivet.name     --notify-email raph@cloud.raphael-jolivet.name     --dbhost localhost     --dbname pleroma     --dbuser pleroma     --dbpass **********     --rum N     --indexable Y     --uploads-dir /home/yunohost.app/pleroma/uploads     --static-dir /home/yunohost.app/pleroma/static     --listen-ip 127.0.0.1     --listen-port 8096     --db-configurable Y'
> 2020-11-04 10:45:28,120: DEBUG - [31m[1m!!! /etc/pleroma/config.exs not found! Please ensure it exists and that PLEROMA_CONFIG_PATH is unset or points to an existing file[0m
> 2020-11-04 10:45:30,829: WARNING - ** (MatchError) no match of right hand side value: {[force: true, output: "/etc/pleroma/config.exs", output_psql: "/tmp/setup_db.psql", domain: "social.raphael-jolivet.name", instance_name: "Raph", admin_email: "raph@cloud.raphael-jolivet.name", notify_email: "raph@cloud.raphael-jolivet.name", dbhost: "localhost", dbname: "pleroma", dbuser: "pleroma", dbpass: "**********", rum: "N", indexable: "Y", uploads_dir: "/home/yunohost.app/pleroma/uploads", static_dir: "/home/yunohost.app/pleroma/static", listen_ip: "127.0.0.1", listen_port: "8096", db_configurable: "Y"], ["J"], []}
> 2020-11-04 10:45:30,832: WARNING -     (pleroma) lib/mix/tasks/pleroma/instance.ex:15: Mix.Tasks.Pleroma.Instance.run/1
> 2020-11-04 10:45:30,836: WARNING -     (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
> 2020-11-04 10:45:30,838: WARNING -     (elixir) lib/code.ex:240: Code.eval_string/3
> 2020-11-04 10:45:30,840: DEBUG - + ynh_exit_properly
> 2020-11-04 10:45:30,842: DEBUG - + local exit_code=1
> 2020-11-04 10:45:30,843: DEBUG - + '[' 1 -eq 0 ']'
> 2020-11-04 10:45:30,845: DEBUG - + trap '' EXIT
> 2020-11-04 10:45:30,846: DEBUG - + set +o errexit
> 2020-11-04 10:45:30,847: DEBUG - + set +o nounset
> 2020-11-04 10:45:30,848: DEBUG - + sleep 0.5
> 2020-11-04 10:45:31,350: DEBUG - + type -t ynh_clean_setup
> 2020-11-04 10:45:31,352: DEBUG - + ynh_clean_setup
> 2020-11-04 10:45:31,354: DEBUG - + ynh_clean_check_starting
> 2020-11-04 10:45:31,357: DEBUG - + '[' -n '' ']'
> 2020-11-04 10:45:31,359: DEBUG - + '[' -n '' ']'
> 2020-11-04 10:45:31,360: DEBUG - + exit 1
> 2020-11-04 10:45:31,520: ERROR - Impossible d’installer pleroma : Une erreur est survenue dans le script d’installation de l’application

**Comment by yalh76** [comment]
I think it's more the space you used for your instance name, try without space.

**Comment by raphaeljolivet** [comment]
Indeed, this works without a space in it.
Does the fix to #132 fixes this as well ?

**Comment by yalh76** [comment]
> 
> 
> Indeed, this works without a space in it.
> Does the fix to #132 fixes this as well ?

nop :/
