### ISSUE TITLE
update 2.2.0

### ISSUE THREAD

**Issue by OniriCorpe** [YunoHost-Apps/pleroma_ynh#146]
Hi ! :)

Pleroma 2.2.0 has been released 

https://git.pleroma.social/pleroma/pleroma/-/releases/v2.2.0

**Comment by OniriCorpe** [comment]
oh and idk how to contact you @yalh76 but i'm ok to help you with this package ^^

**Comment by yalh76** [comment]
> oh and idk how to contact you @yalh76 but i'm ok to help you with this package ^^

Hi :)

Welcome on Board ^^
Feel free to do a PR on the testing branch for pleroma 2.2 ^^

I'm usually connected on the yunohost app développer Chanel on Matrix if you want to contact me directly :)
