### ISSUE TITLE
-bash: --moderator: command not found

### ISSUE THREAD

**Issue by morta5** [YunoHost-Apps/pleroma_ynh#154]
**Versions**
- Hardware: Raspberry Pi at home
- YunoHost version:  4.1.7.1
- I have access to my server: SSH / WEBADMIN / KEYBOARD
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: yes
  - If yes, please explain: I have installed Adguard Home manually
- I tried to install the latest version

**To Reproduce**
    ```sh
    sudo yunohost app install pleroma
    ```

**Expected behavior**
Be able to access Pleroma from the web
**Logs**
https://paste.yunohost.org/raw/fevaxidoki

It seems to me like the service did not start in the 60 seconds the script waited for it to start, but I am not sure

**Comment by yalh76** [comment]
Hi it seems that's not a service issue the error is:
```
2021-02-14 21:59:34,267: DEBUG - + su pleroma -s /bin/bash -lc '/var/www/pleroma/pleroma/bin/pleroma_ctl user new farshidhakimy farshidhakimy@domain4.tld --password ********** --moderator --admin -y'
2021-02-14 21:59:34,671: DEBUG - + ynh_exit_properly
2021-02-14 21:59:34,672: WARNING - -bash: --moderator: command not found
```

maybe there is something weird with your password like a space or something ....

**Comment by morta5** [comment]
Oh got it. It would make sense if it is something with the password
