### ISSUE TITLE
Missing /var/lib/pleroma in upgrade to 2.2.2

### ISSUE THREAD

**Issue by hieronymousch** [YunoHost-Apps/pleroma_ynh#157]
Hi,

i just tested the upgrade, which worked fine but I did notice that pleroma expects data to live in /var/lib/pleroma. I solved it by making a symbolic link to the yunohost.app 
sudo ln -s /home/yunohost.app/pleroma/ /var/lib/pleroma

**Comment by yalh76** [comment]
If pleroma look at /var/lib/pleroma... there is a problem because installation explicitly define other paths:
https://github.com/YunoHost-Apps/pleroma_ynh/blob/059ddc457aabe6962f5960612ed2dc1db53daeeb/scripts/install#L196-L219
