### ISSUE TITLE
[SECURITY] $final_path, which contains the db password, is readable by all users

### ISSUE THREAD

**Issue by Jules-Bertholet** [YunoHost-Apps/pleroma_ynh#163]
### Describe the bug

`$final_path`, which contains the password to the Pleroma PostgreSQL database, is readable by all users.

### Expected behavior

The permissions of the files inside `$final_path` are restricted so users can't get the db password.

**Comment by yalh76** [comment]
There is already a patch ongoing => https://github.com/YunoHost/yunohost/pull/1188
