### ISSUE TITLE
Upgrade to pleroma 2.4.0~ynh1 from 2.3.0~ynh3 succeeds but results in 502 bad gateway 

### ISSUE THREAD

**Issue by lightnin** [YunoHost-Apps/pleroma_ynh#178]
Upgrade to 2.4.0~ynh1 from previous release results in 502 afterwards on YunoHost 4.2.8.1 (stable) on Rpi4.

### Steps to reproduce
Upgrade via webadmin.

### Expected behavior

Successful upgrade with working pleroma install afterwards.

Logs:
https://paste.yunohost.org/raw/xijanaleza

Many thanks for making pleroma available on Yunohost!

**Comment by yalh76** [comment]
Seems weird, tests were ok.
You should look if the pleroma service is running. 
can be done on the YunoHost webadmin of from the command line `service pleroma restart`

**Comment by lightnin** [comment]
Thanks for looking at this so quickly!
Tried rebooting, still get 502. Tried restart, still 502. Here's service status:

![Screenshot 2021-08-28 at 15 37 01](https://user-images.githubusercontent.com/1538027/131219798-22c31302-5d0e-4bb4-83d7-47b584c9c6ee.png)


URL instance is here:
https://masto.amosamos.net/

**Comment by lightnin** [comment]
There's quite a lot of pleroma running, in spite of the 502.
![Screenshot 2021-08-28 at 18 47 07](https://user-images.githubusercontent.com/1538027/131224947-3b590692-d56c-457a-9e42-99482b1baaa9.png)

**Comment by yalh76** [comment]
ok, can you check the value of the port indicated in `/etc/pleroma/config.exs` L9. and if it's the same as in `/etc/nginx/conf.d/your_pleroma_domain/pleroma.conf` L16

**Comment by lightnin** [comment]
config.exs:
config :pleroma, Pleroma.Web.Endpoint,
   url: [host: "masto.amosamos.net", scheme: "https", port: 443],
   http: [ip: {127, 0, 0, 1}, port: 8095],

Line 16 of pleroma.conf:
  proxy_pass http://localhost:8095;

So yep, the same.

Gonna have to restore the backup now unfortunately, as I need my instance for documentation this week. But can try upgrade again next week.

**Comment by lightnin** [comment]
@yalh76 I see there is a 2.4.1 release out now - do you think it's likely to resolve this issue?

**Comment by lightnin** [comment]
Installed the 2.4.1 release and no 502s, everything seems A ok. :) Thanks!
