### ISSUE TITLE
Why substituting spaces in name with underscores?

### ISSUE THREAD

**Issue by fflorent** [YunoHost-Apps/pleroma_ynh#182]
In installation script, we can see this line of code:
```bash
name="${YNH_APP_ARG_NAME// /_}"
```

I wonder why this substitution. If I edit the name in `/etc/pleroma/config.exs` directly, putting spaces in it, I don't get any error.

Is there any history around this? The reasons is still nowadays relevant?

Thanks :pray:

**Comment by yalh76** [comment]
Hi, 

Long story short: `$name` is used at https://github.com/YunoHost-Apps/pleroma_ynh/blob/e6d9935af254018baf326281662c55407170694d/scripts/install#L193-L213

And with spaces in the instance name, `pleroma_ctl instance gen` doesn't work... and I didn't find a way to find a solution other than removing spaces in the instance name ...
