### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by vincentux** [YunoHost-Apps/pleroma_ynh#20]
Installation fail via l'interface UI

>Debian 9.7 64bit (Linux 4.9.0-8-amd64)
yunohost 3.4.2.2 (stable)
yunohost-admin 3.4.2 (stable)
moulinette 3.4.2 (stable)
ssowat 3.4.2 (stable) 

```
2019-02-01 15:31:35,241: ERROR - Une erreur inattendue est survenue
Traceback (most recent call last):
  File "/usr/lib/moulinette/yunohost/app.py", line 836, in app_install
    args=args_list, env=env_dict
  File "/usr/lib/moulinette/yunohost/hook.py", line 358, in hook_exec
    command.append(cmd.format(script=cmd_script, args=cmd_args))
ValueError: unmatched '{' in format
```

**Comment by yalh76** [comment]
Can you try to install it from the command line ?
using:
```bash
yunohost tools update
yunohost app install pleroma --debug
```

**Comment by yalh76** [comment]
Or you can go in the admin panel in: Tools / Logs / Install application « pleroma »
and click on the top right green button: Share with yunohost and post here the link to the pastebin

**Comment by vincentux** [comment]
Installation CLI

```
yunohost tools update
yunohost app install pleroma --debug
```

https://framabin.org/p/?9482b551a7953b82#ri0BqRMyWfe+VsCj7MGnqFbwSpuHi8/yQcZEDyCnCUw=

**Comment by yalh76** [comment]
Very weird, it look like your Yunohost is broken.
Here is a log from a pleroma installation 2 minutes ago: https://paste.yunohost.org/gomeducudu.sql
Your log miss the 30 first lines...

**Comment by yalh76** [comment]
Are you able to install other packages ?

**Comment by vincentux** [comment]
Arf, désolé j'ai pas répondu tout de suite....  
en fait je suis partie sur une install d'Hubzilla, qui c'est bien passé.

**Comment by yalh76** [comment]
OK alors je ferme ^^

**Comment by Duponin** [comment]
Hello,

I tried to install it today and it only worked with CLI, when I tried from web interface it failed:

```
2019-02-24 21:01:23,105: ERROR - An unexpected error occured: 
Traceback (most recent call last):
  File "/usr/lib/moulinette/yunohost/app.py", line 836, in app_install
    args=args_list, env=env_dict
  File "/usr/lib/moulinette/yunohost/hook.py", line 358, in hook_exec
    command.append(cmd.format(script=cmd_script, args=cmd_args))
ValueError: Single '}' encountered in format string
Traceback (most recent call last):
  File "/usr/lib/moulinette/yunohost/app.py", line 836, in app_install
    args=args_list, env=env_dict
  File "/usr/lib/moulinette/yunohost/hook.py", line 358, in hook_exec
    command.append(cmd.format(script=cmd_script, args=cmd_args))
ValueError: Single '}' encountered in format string
```

Anyway, thank you for providing this app :+1:

**Comment by yalh76** [comment]
I will check that and let you know

**Comment by yalh76** [comment]
Just tested from the web interface after an update of pleroma to 0.9.9.: installation works. If you can test ?

**Comment by Duponin** [comment]
Test done few minutes ago. Result: `Working`

Steps:
1. New install (VM)
2. Create a new user
3. Add a domain
4. Install Pleroma on new domain, new user as admin

Kind of weird that works on first try. I'll dig to see if I can make it fail.\
On the other YNH installation, I installed some applications and did system upgrade before Pleroma installation.
