### ISSUE TITLE
Auto-updater is not working

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/pleroma_ynh#201]
Seems, not working well :https://github.com/YunoHost-Apps/pleroma_ynh/pull/200/files

_Originally posted by @yalh76 in https://github.com/YunoHost-Apps/pleroma_ynh/issues/198#issuecomment-1140420244_

**Comment by tituspijean** [comment]
(I have disabled the Actions altogether, pending resolution of the issue).

**Comment by yalh76** [comment]
seems working for now => https://github.com/YunoHost-Apps/pleroma_ynh/pull/229
