### ISSUE TITLE
Restore from backup onto Ynh 11 results in 502s: exec: /var/www/pleroma/live/erts-10.7.2.17/bin/erlexec: not found

### ISSUE THREAD

**Issue by lightnin** [YunoHost-Apps/pleroma_ynh#206]
1.Fresh install of 11.0.9
2. Restore backup of previous system, including pleroma.
Logs from restoration of Pleroma archive: 
https://paste.yunohost.org/raw/gonafuwavi
3. Pleroma service fails to start.: https://paste.yunohost.org/ipoderuzod
4. Regen-conf nginx as per migration instructions
5. Upgrade apps / packages.
6. yunohost app upgrade -F pleroma
https://paste.yunohost.org/raw/pimafiyofu
(logs from second time)
9. Still 502ing.

Note, from service record in: https://paste.yunohost.org/ipoderuzod
Sep 05 17:51:05 pleroma[1025]: /var/www/pleroma/live/releases/2.4.3/../../erts-10.7.2.17/bin/erl: 12: exec: /var/www/pleroma/live/erts-10.7.2.17/bin/erlexec: not found

**Comment by lightnin** [comment]
Hi @tituspijean wondering if you can suggest any further actions for me to try on this one?

**Comment by tituspijean** [comment]
Can you try the following fix? `sudo yunohost app upgrade pleroma -u https://github.com/YunoHost-Apps/pleroma_ynh/tree/fix-force-upgrade -F`

**Comment by lightnin** [comment]
Amazing! A thousand thanks, @tituspijean !! It works. :)
