### ISSUE TITLE
500's "timed out because it queued and checked out the connection for longer than 15000ms"

### ISSUE THREAD

**Issue by lightnin** [YunoHost-Apps/pleroma_ynh#209]
For several months now I see 500 errors reported by pleroma when browsing  my timeline. This has been consistent across a new install of Yunohost due to problems with migration to 11.
Below are relevant logs. Not sure if this should be reported upstream, or if it's related to Ynh config / resource limits. 
In general the machine doesn't seem to be overwhelmed - plenty of processor and memory left.

My timeline consists mostly of videos. You can see it here:
https://masto.amosamos.net/lightnin

Rpi4
Yunohost 11

Thanks!

Logs:

Sep 26 08:11:52 net pleroma[943]: 08:11:52.446 request_id=FxhXhnKWzKyP2HMAAB-j [info] Sent 500 in 15178ms
Sep 26 08:12:25 net pleroma[943]: 08:12:25.102 [error] Postgrex.Protocol (#PID<0.6743.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.19169.0> timed out because it queued and checked out the connection for longer than 15000ms
Sep 26 08:12:25 net pleroma[943]: 08:12:25.115 request_id=FxhXjgzNjfxgHbYAAMSh [info] Sent 500 in 15197ms
Sep 26 08:12:56 net pleroma[943]: 08:12:56.836 [error] Postgrex.Protocol (#PID<0.6740.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.19206.0> timed out because it queued and checked out the connection for longer than 15000ms
Sep 26 08:12:56 net pleroma[943]: 08:12:56.853 request_id=FxhXlXDAfFg8MwUAACEj [info] Sent 500 in 15193ms
Sep 26 08:13:29 net pleroma[943]: 08:13:29.073 [error] Postgrex.Protocol (#PID<0.6744.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.19245.0> timed out because it queued and checked out the connection for longer than 15000ms
Sep 26 08:13:29 net pleroma[943]: 08:13:29.085 request_id=FxhXnPGyWwMHnIMAAMXB [info] Sent 500 in 15196ms

**Comment by yalh76** [comment]
At least you should look at issues at https://git.pleroma.social/search?group_id=3&project_id=2&repository_ref=develop&scope=issues&search=+timed+out+because+it+queued+and+checked+out+the+connection+for+longer+than+15000ms

There are some issue with the same log errors.

let's know if and how you solved your issue

**Comment by lightnin** [comment]
I removed Nextcloud and several other apps from my Ynh server and I no longer get 500s. (Though it could have been fixed by various other normal upgrades to the system) Note that there never appeared to be much load on the system, so it didn't seem to be caused from running out of RAM / CPU. @yalh76
