### ISSUE TITLE
Can't login into any Pleroma account

### ISSUE THREAD

**Issue by ZeAntwan** [YunoHost-Apps/pleroma_ynh#216]
### Describe the bug

After installing (and removing then reinstalling) Pleroma on my Yunohost server, I cannot get access to either, the pre-setup admin account during the install process, or a newly created account.
I tried to access the website from Yunohost panel hoping it would have me connected, with no success.
I tried connecting directly using the website login, no success (Upon inspecting the browser console, I get a HTTP 400 Error)

*A clear and concise description of what the bug is.*

### Context

- Hardware: VPS from OVH
- YunoHost version: x.x.x
- I have access to my server: Through SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No
- Using, or trying to install package version/branch: Latest using Yunohost catalog

### Steps to reproduce

   1. Install app on a free domain
   2. Set app to allow registering for non Yunohost users
   3. Go to app
   4. Notice that you ar not logged in
   5. Try to log in
   6. Open browser console to see error

### Expected behavior

I expected to be connected and or be allowed to connect (unless this is not available as per the disclaimer about HTTP in the readme)

**Comment by tr1p0p** [comment]
Yeah same issue. Pleroma seem to handle account creation and admin like... REALLY bad. Badly like "you can connect once and never again" bad

**Comment by walterebert** [comment]
This problem occurs when your are logged in in the YunoHost Portal. Logging out of the Portal and then logging into Pleroma with the same user works.

**Comment by blogdemoi** [comment]
Hum, the same thing happens to me. I installed Pleroma, created a user, but can't log in. "Invalid credentials", and when I create a reset link and changes the psswd, same thing. Tried on Firefox and Brave.

What to do? 

Thank you.

**Comment by blogdemoi** [comment]
Edit: After trying a lot I realized that I can login with my yunohost user psswd but not with the psswd used during the Pleroma installation.
