### ISSUE TITLE
Static directory not removed at uninstall

### ISSUE THREAD

**Issue by bugsysop** [YunoHost-Apps/pleroma_ynh#233]
If you uninstall Pleroma, the static directory (`/home/yunohost.app/pleroma/static/`) is not removed or archived by the uninstall script of YNH... 

This can be a problem in case of later installation of a _new or clean instance_ of Pleroma for a new project for example.

The good idea can be to make a _backup_ somewhere, as the `stactic/` directory contain all the _custom_ assets and files of the removed instance.

**Comment by yalh76** [comment]
If someone want to delete the folder `/home/yunohost.app/pleroma/` during removal of pleroma_ynh, it should add the `--purge` option. like all apps keeping datas in `/home/yunohost.app/`
