### ISSUE TITLE
Failure to update Pleroma

### ISSUE THREAD

**Issue by HasturTime** [YunoHost-Apps/pleroma_ynh#234]
I run a small Pleroma instance for me and a couple of friends. It's been up for a couple of years.
We started to experience a lot of errors, so I decided to try and update it

I'm a novice at Linux. More used at .net

I run an OTP installation in a DO droplet

I followed the instructions on https://docs-develop.pleroma.social/backend/administration/updating/

I got some error messages, but I don't remember them now

Everything seemed to be running well afterward but now I get 502 Bad Gateway

If I run: systemctl status pleroma.service

I get
● pleroma.service - Pleroma social network

Loaded: loaded (/etc/systemd/system/pleroma.service; enabled; vendor preset: enabled)

Active: failed (Result: exit-code) since Tue 2023-02-14 11:07:32 UTC; 1min 7s ago

Process: 965 ExecStart=/opt/pleroma/bin/pleroma start (code=exited, status=203/EXEC)

Main PID: 965 (code=exited, status=203/EXEC)

Feb 14 11:07:32 pleroma-thyme systemd[1]: pleroma.service: Main process exited, code=exited, status=203/EXEC

Feb 14 11:07:32 pleroma-thyme systemd[1]: pleroma.service: Failed with result 'exit-code'.

Feb 14 11:07:32 pleroma-thyme systemd[1]: pleroma.service: Scheduled restart job, restart counter is at 5.

Feb 14 11:07:32 pleroma-thyme systemd[1]: Stopped Pleroma social network.

Feb 14 11:07:32 pleroma-thyme systemd[1]: pleroma.service: Start request repeated too quickly.

Feb 14 11:07:32 pleroma-thyme systemd[1]: pleroma.service: Failed with result 'exit-code'.

Feb 14 11:07:32 pleroma-thyme systemd[1]: Failed to start Pleroma social network.

**Comment by yalh76** [comment]
You should look at the upstream git => https://git.pleroma.social/pleroma/pleroma/
