### ISSUE TITLE
Javascript Execution Vulnerability

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/pleroma_ynh#245]
https://github.com/YunoHost-Apps/akkoma_ynh/issues/29

**Comment by seanking2919** [comment]
We just released a patch to fix the OEmbed HTML issue today. https://pleroma.social/announcements/2023/05/26/pleroma-release-2.5.2/

**Comment by seanking2919** [comment]
Update: Version 2.5.2 has been merged into this repo.
