### ISSUE TITLE
Install in a sub_dir

### ISSUE THREAD

**Issue by yalh76** [YunoHost-Apps/pleroma_ynh#27]

**Comment by yalh76** [comment]
tested on and not working

**Comment by vincentux** [comment]
Je viens de installer Pleroma_ynh avec un "sous-domaine". 
Toute l'installation c'est bien déroulée mais je n'arrive pas à fédérer avec les autres instances ... 
Est-ce lié ???

**Comment by yalh76** [comment]
> 
> 
> Je viens de installer Pleroma_ynh avec un "sous-domaine".
> Toute l'installation c'est bien déroulée mais je n'arrive pas à fédérer avec les autres instances ...
> Est-ce lié ???

rien à voir.
Là l'objectif c'est de pouvoir installer un jour pleroma dans: `https://mondomaine.fr/pleroma`

**Comment by Duponin** [comment]
Hello,

Je me souviens d'une discussion que j'ai eu avec un des developpeurs (impossible de la retrouver, trop ancienne) qui disait que ça serait beaucoup trop compliqué à gérer. Pleroma n'est pas conçu pour fonctionner sans être à la racine du domaine ; le code par du principe que tout commence à `/`.

Cette discussion a été faite avec Rin mais je conseillerai de passer sur `pleroma-dev` sur Freenode pour avoir une confirmation.

Autrement je dirais que la seule solution (mais pas propre) est de faire une traduction d'URL entre le nginx et Pleroma pour ajouter ou retirer le `sub_dir`. Mais risque d'explosion !

**Comment by yalh76** [comment]
won't be possible ^^
