### ISSUE TITLE
Implement LDAP authentication

### ISSUE THREAD

**Issue by yalh76** [YunoHost-Apps/pleroma_ynh#28]

**Comment by yalh76** [comment]
No LDAP support for known but maybe in the future:
https://git.pleroma.social/pleroma/pleroma/issues/203

**Comment by yalh76** [comment]
Ldap implemented in pleroma
trying to implement it on https://github.com/YunoHost-Apps/pleroma_ynh/tree/ldap

**Comment by yalh76** [comment]
ldap only available in the develop branch for now

**Comment by Thatoo** [comment]
I have modified README.md to include the LDAP support as you can see here https://github.com/Thatoo/pleroma_ynh but I can't make a PR from my master branch to your testing branch (only to your master).
I know it is available only on testing branch so I don't want to make a PR to master for now.
Is it possible to do so or should I wait that you finish testing and that you merge your testing branch into your master branch?

**Comment by yalh76** [comment]
> 
> 
> I have modified README.md to include the LDAP support as you can see here https://github.com/Thatoo/pleroma_ynh but I can't make a PR from my master branch to your testing branch (only to your master).
> I know it is available only on testing branch so I don't want to make a PR to master for now.
> Is it possible to do so or should I wait that you finish testing and that you merge your testing branch into your master branch?

It's because you made the changes in the master branch of your fork. Would be better to do in the Testing Branch

two options:

1. you merge https://github.com/YunoHost-Apps/pleroma_ynh/tree/testing into https://github.com/Thatoo/pleroma_ynh and then you would be able to to do a PR from https://github.com/Thatoo/pleroma_ynh to https://github.com/YunoHost-Apps/pleroma_ynh/tree/testing (best option)
2. You redo all the changes you want into https://github.com/Thatoo/pleroma_ynh/tree/testing and then make a PR to https://github.com/YunoHost-Apps/pleroma_ynh/tree/testing

But at the end of the day, if we say in the readme that ldap is supported, we need to explain how or to implement it automatically in the package.

For ending, actual pleroma_ynh is based on pleroma v0.9.9999, and pleroma v0.9.9999 don't support ldap.
Ldap in for now in the develop branch of pleroma and has not been released.

**Comment by Thatoo** [comment]
Thank you, I understand. I mean I think I understand...

And I guess it will wait till LDAP is supported by pleroma.

**Comment by yalh76** [comment]
Ldap implemented
