### ISSUE TITLE
Upgrade Fails

### ISSUE THREAD

**Issue by gyratory** [YunoHost-Apps/pleroma_ynh#33]
It looks like there's some conflict when pulling the git origin remote. Should I use Archivist to back up the core files and `git reset --hard` and manually pull master before upgrading?

Log file attached.
[pleroma_ynh.log](https://github.com/YunoHost-Apps/pleroma_ynh/files/2854568/pleroma_ynh.log)

**Comment by yalh76** [comment]
Problem solved in last PR.
I added:
```
git reset --hard
git pull --quiet
```
in the upgrade script

**Comment by gyratory** [comment]
`yunohost app upgrade pleroma` didn't work. I had to manually clear my configuration files before updating worked correctly. Everything is working now, and I was able to reapply my custom configuration changes afterwards.
