### ISSUE TITLE
Installation fails 

### ISSUE THREAD

**Issue by ironm0nk3y** [YunoHost-Apps/pleroma_ynh#58]
Hello, Installation fails due to not being able to make SSL connection:
"2019-03-31 04:18:45,359: DEBUG - + ynh_exit_properly
2019-03-31 04:18:45,359: WARNING - GnuTLS: Error in the pull function.
2019-03-31 04:18:45,360: DEBUG - + local exit_code=4
2019-03-31 04:18:45,360: WARNING - Unable to establish SSL connection."

Appears the link for the key:
"https://packages.erlang-solutions.com/debian/erlang_solutions.asc" 
Takes a long time to resolve and ends up timing out. Installing the key manually allows for allows for rerun of install and instance being created.

Thanks for putting this install package together! This is just what I was looking for.

Thanks!

**Comment by yalh76** [comment]
Hi @ironm0nk3y, 

I've seen that during testing, sometime the key took time to retrieve, I will check if I can use a workaround. 

[I planed to use ynh_add_secure_repos__2 instead of adding directly the repo](https://github.com/YunoHost-Apps/pleroma_ynh/issues/59)

Thanks for the report

**Comment by yalh76** [comment]
ynh_add_secure_repos__3 implemented
