### ISSUE TITLE
Failed to upgrade

### ISSUE THREAD

**Issue by drecksky** [YunoHost-Apps/pleroma_ynh#64]
Pleroma fails to upgrade via web and cli.

[Log here](https://paste.yunohost.org/raw/arihogegub)

**Comment by yalh76** [comment]
Hi @drecksky 

Seems like an internal pleroma error during pleroma compilation: L1465 ` WARNING - warning: function Pleroma.User.Info.roles/1 is undefined or private`

I've updated the package, can you try to make a new upgrade and let me know?

**Comment by drecksky** [comment]
Hi @yalh76 

The upgrade didn't work, a new log is [here](https://paste.yunohost.org/raw/peqopehija).

**Comment by yalh76** [comment]
I think I solved the issue in https://github.com/YunoHost-Apps/pleroma_ynh/pull/66

You can test it now using `yunohost app upgrade pleroma -u https://github.com/YunoHost-Apps/pleroma_ynh/tree/testing --debug`

**Comment by drecksky** [comment]
Hi, @yalh76 

Unfortunately, no luck. New log is [here](https://paste.yunohost.org/raw/fuxihuciha).

**Comment by buzzworkers** [comment]
same here, upgrade failed using the one-liner above : https://paste.yunohost.org/raw/owejelabec

**Comment by yalh76** [comment]
Hi@drecksky

I push a new version of pleroma: v0.9.999**9** can you try to upgrade using: `yunohost app upgrade pleroma -u https://github.com/YunoHost-Apps/pleroma_ynh/tree/v0.9.9999 --debug`

**Comment by yalh76** [comment]
Hi @buzzworkers 

Your problem is different, during dependencies upgrade, it tries to remove ssh :/ but I don't know why...
Maybe you can try also to upgrade pleroma using `yunohost app upgrade pleroma -u https://github.com/YunoHost-Apps/pleroma_ynh/tree/v0.9.9999 --debug`

**Comment by drecksky** [comment]
Hi @yalh76 

The upgrade to v0.9.9999 failed; new log [here](https://paste.yunohost.org/raw/suvesolati).

**Comment by yalh76** [comment]
argg

> 
> 
> Hi @yalh76
> 
> The upgrade to v0.9.9999 failed; new log [here](https://paste.yunohost.org/raw/suvesolati).

arrrggg, still the same issue `2019-04-11 19:05:46,978: WARNING - warning: function Pleroma.User.Info.roles/1 is undefined or private`

Maybe you can open an issue at https://git.pleroma.social/pleroma/pleroma/issues, it seems not related to yunohost package ?

**Comment by buzzworkers** [comment]
> Hi @buzzworkers
> 
> Your problem is different, during dependencies upgrade, it tries to remove ssh :/ but I don't know why...
> Maybe you can try also to upgrade pleroma using `yunohost app upgrade pleroma -u https://github.com/YunoHost-Apps/pleroma_ynh/tree/v0.9.9999 --debug`

1901 ERROR unable to download https://github.com/YunoHost-Apps/pleroma_ynh/archive/v0.9.9999.zip

**Comment by yalh76** [comment]
> 
> 
> > Hi @buzzworkers
> > Your problem is different, during dependencies upgrade, it tries to remove ssh :/ but I don't know why...
> > Maybe you can try also to upgrade pleroma using `yunohost app upgrade pleroma -u https://github.com/YunoHost-Apps/pleroma_ynh/tree/v0.9.9999 --debug`
> 
> 1901 ERROR unable to download https://github.com/YunoHost-Apps/pleroma_ynh/archive/v0.9.9999.zip

Sorry this branche was merged in testing yesterday.
You can now test it using `yunohost app upgrade pleroma -u https://github.com/YunoHost-Apps/pleroma_ynh/tree/testing --debug`

**Comment by buzzworkers** [comment]
> > > Hi @buzzworkers
> > > Your problem is different, during dependencies upgrade, it tries to remove ssh :/ but I don't know why...
> > > Maybe you can try also to upgrade pleroma using `yunohost app upgrade pleroma -u https://github.com/YunoHost-Apps/pleroma_ynh/tree/v0.9.9999 --debug`
> > 
> > 
> > 1901 ERROR unable to download https://github.com/YunoHost-Apps/pleroma_ynh/archive/v0.9.9999.zip
> 
> Sorry this branche was merged in testing yesterday.
> You can now test it using `yunohost app upgrade pleroma -u https://github.com/YunoHost-Apps/pleroma_ynh/tree/testing --debug`

This is what I did the first time (see above with the ssh removal trial that makes no sense) just to make sure I tried it again just now and this is the log file : https://paste.yunohost.org/raw/exixukowir

**Comment by buzzworkers** [comment]
This new log makes no sense...of course I have SSH installed...I'm using ssh to launch the upgrade command in the first place.... ??

**Comment by yalh76** [comment]
> This is what I did the first time (see above with the ssh removal trial that makes no sense) just to make sure I tried it again just now and this is the log file : https://paste.yunohost.org/raw/exixukowir

Well, you still have the same problem and I don't know how to solve it, I'm a Linux beginner.

Can you ask help in the [forum](https://forum.yunohost.org/) or with Matrix (#freenode_#yunohost:matrix.org)

**Comment by yalh76** [comment]
> 
> 
> This new log makes no sense...of course I have SSH installed...I'm using ssh to launch the upgrade command in the first place.... ??

L1733, it wants to remove ssh even if L1635 ssh is in the list of dependencies...

**Comment by xaloc33** [comment]
I think that I had a similar issue upgrading and I wasn't able to restore the backup.

I finally solved reverting elixir to 1.7.4 because the 1.8 version depends on esl-erlang instead of erlang which makes the restore of the app crash when it tries to install the dependencies.

I don't know if it is actually related to any of this but I thought it may help someone.

**Comment by drecksky** [comment]
Restoring the database failed for me as well; I tried rolling back elixer but the result was the same. After a couple days of tinkering, I ended up reinstalling and starting anew. Thank you to @xaloc33 and especially @yalh76 ; I appreciate your time and help.

**Comment by yalh76** [comment]
> 
> 
> I think that I had a similar issue upgrading and I wasn't able to restore the backup.
> 
> I finally solved reverting elixir to 1.7.4 because the 1.8 version depends on esl-erlang instead of erlang which makes the restore of the app crash when it tries to install the dependencies.
> 
> I don't know if it is actually related to any of this but I thought it may help someone.

do you have the logs with Elixir 1.7.4 ?

**Comment by yalh76** [comment]
@drecksky 

Sorry you had to reinstall from scratch :///

**Comment by drecksky** [comment]
No worries; poo poo happens and the instance had minimal activity anyway. I'm thinking I broke something myself whilst tinkering with stuff earlier. 

After reinstalling, I upgraded to the Test branch without issue so I'm feeling confident now.

**Comment by xaloc33** [comment]
> > I think that I had a similar issue upgrading and I wasn't able to restore the backup.
> > I finally solved reverting elixir to 1.7.4 because the 1.8 version depends on esl-erlang instead of erlang which makes the restore of the app crash when it tries to install the dependencies.
> > I don't know if it is actually related to any of this but I thought it may help someone.
> 
> do you have the logs with Elixir 1.7.4 ?

Here you have the logs I got restoring the backup with Elixir 1.7.4 :
https://paste.yunohost.org/raw/exobidukod

**Comment by yalh76** [comment]
> 
> 
> I think that I had a similar issue upgrading and I wasn't able to restore the backup.
> 
> I finally solved reverting elixir to 1.7.4 because the 1.8 version depends on esl-erlang instead of erlang which makes the restore of the app crash when it tries to install the dependencies.
> 
> I don't know if it is actually related to any of this but I thought it may help someone.

I will try to switch dependencies to esl-erlang in #70

**Comment by buzzworkers** [comment]
> @drecksky
> 
> Sorry you had to reinstall from scratch :///

I want to re-install from scratch, can I just use : yunohost app install pleroma -u https://github.com/YunoHost-Apps/pleroma_ynh/tree/testing --debug ?

**Comment by yalh76** [comment]
> 
> 
> > @drecksky
> > Sorry you had to reinstall from scratch :///
> 
> I want to re-install from scratch, can I just use : yunohost app install pleroma -u https://github.com/YunoHost-Apps/pleroma_ynh/tree/testing --debug ?

Yes you can use that or `yunohost app install pleroma -u https://github.com/YunoHost-Apps/pleroma_ynh/tree/testing --debug` it will install pleroma with esl-erlang for elixir 1.8 dependency

**Comment by buzzworkers** [comment]
I had to remove pleroma -u for it to install, but even like that install process fail :/ 
command : yunohost app install https://github.com/YunoHost-Apps/pleroma_ynh/tree/testing --debug

log : https://paste.yunohost.org/raw/nuyutojabo

I'm not sure what's happening here, but I'm on a clean yunohost install and it seems there is issues with ssh and earlang and java ?

**Comment by yalh76** [comment]
@buzzworkers Yes your yunohost doesn't seems very clean.
Maybe you can start doing `yunohost tools update && yunohost tools upgrade`
And maybe: `apt autoremove`

**Comment by buzzworkers** [comment]
My yunohost is a fresh brand new install, I have just a few apps installed: rainloop, custom web app for a blog, netdata/grafana, that's it...

**Comment by yalh76** [comment]
> 
> 
> My yunohost is a fresh brand new install, I have just a few apps installed: rainloop, custom web app for a blog, netdata/grafana, that's it...

In that case, I don't understand why some java packages needs to be removed...

**Comment by yalh76** [comment]
I have switched back dependencies to original.
You can upgrade from the cli doing: `yunohost app upgrade pleroma -u https://github.com/YunoHost-Apps/pleroma_ynh --debug`

Let me know if you have some issue upgrading

**Comment by yalh76** [comment]
no news, closing

**Comment by buzzworkers** [comment]
Sorry for the no-reply, I was out for a while..by the way I installed v0.9.9999 and it's all running fine

**Comment by xaloc33** [comment]
Sorry for not answering sooner, I've had plenty of work lately... I finally had the time to try to update. Doing the usual : ```yunohost app upgrade pleroma```
didn't work (same issue with packages not being removed) but with: ```yunohost app upgrade pleroma -u https://github.com/YunoHost-Apps/pleroma_ynh --debug```  everything run smoothly!

Thank you @yalh76 and sorry for the lack of feedback
