### ISSUE TITLE
Running commands as pleroma user not working

### ISSUE THREAD

**Issue by brickcamp** [YunoHost-Apps/pleroma_ynh#82]
Hi there,

I installed pleroma via yunohost and then tried to add a user via ssh. But when I try to do so, I get this:

![Terminal](https://user-images.githubusercontent.com/49322756/59375113-bcbcd180-8d4d-11e9-8dec-57997cee34da.png)

The admin user of yunohost seems to have no authority to run commands as pleroma user. So I tried to login as pleroma user directly - but the "administrator password", I entered in the install form, isn't working for the pleroma user.

Am I doing something wrong? Or is this a bug - maybe related to #28 ?

**Comment by yalh76** [comment]
Hi @brickcamp 

No it's not related to #28.

Seems that the admin user is not allowed to execute comamnd as pleroma user

1. You can try to execute : `sudo usermod -aG sudo,admin pleroma`
2.  or you first need to log as root doing: `su` and then you are able to launch the command: `sudo -u pleroma MIX_ENV=prod mix pleroma.user new ...`

**Comment by brickcamp** [comment]
admin group doesn't exist, but switching to root before running the command worked - thanks 🙂
