### ISSUE TITLE
Upgrade to Pleroma v1.0.1

### ISSUE THREAD

**Issue by xaloc33** [YunoHost-Apps/pleroma_ynh#88]
Hi,

Pleroma has finally reached v1 :) would be possible to upgrade to the latest release (v1.0.1)?

Thanks,
Xaloc

**Comment by yalh76** [comment]
Hi @xaloc33 

Have you checked: https://github.com/YunoHost-Apps/pleroma_ynh/pull/87 ?

**Comment by xaloc33** [comment]
Nop 😅 sorry and thanks for your work.
