### ISSUE TITLE
installation is failing

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/pleroma_ynh#89]
today i tied to reintall my not anymore working pleroma installtion...
i tied manytimes but it did not work.
please have a look:

https://paste.yunohost.org/raw/uqezasasod

thanks for your help

**Comment by yalh76** [comment]
Seems you have a dependency issue. Better to wait a few days, there is an ongoing PR https://github.com/YunoHost-Apps/pleroma_ynh/pull/87 to a 1.0.X without dependencies needs

**Comment by StalinEXE** [comment]
> Seems you have a dependency issue. Better to wait a few days, there is an ongoing PR #87 to a 1.0.X without dependencies needs

Hope to see this release asap

**Comment by yalh76** [comment]
You can try to install the testing version from the command line: `yunohost app install https://github.com/YunoHost-Apps/pleroma_ynh/tree/testing --debug`

**Comment by yalh76** [comment]
Release merged, I let you test it. I close that issue for now but feel free to reopen it
