### ISSUE TITLE
Could Pleroma be upgraded without waiting for LDAP?

### ISSUE THREAD

**Issue by spctrlth** [YunoHost-Apps/pleroma_ynh#92]
We just had someone in the pleroma support chat who installed on yunohost and apparently the installed version is still pre 1.0

I see at https://github.com/YunoHost-Apps/pleroma_ynh/pull/87 that the current problem is that OTP doesn't have LDAP. But would it be possible to release sooner, without LDAP, and add it later? AFAIK LDAP isn't working now either, so upgrading to a newer version seems strictly better to me than waiting until maybe someone fixes whatever causes OTP to not include LDAP.

**Comment by yalh76** [comment]
Hi @spctrlth, 

For now it's not just LDAP, there is also the [--static-dir argument issue](https://git.pleroma.social/pleroma/pleroma/issues/1289).

As you can see at https://github.com/YunoHost-Apps/pleroma_ynh/pull/87/commits, I've tried various pleroma versions, 

I need to test with 1.1.7 but as far as I've seen, --static-dir argument issue is still not solved...

**Comment by yalh76** [comment]
OTP version is ready in the testing, if you can test it:
- install : `yunohost app install https://github.com/YunoHost-Apps/pleroma_ynh/tree/testing --debug`
- upgrade : `yunohost app upgrade pleroma -u https://github.com/YunoHost-Apps/pleroma_ynh/tree/testing --debug`
And let me know. before merging in master.

**Comment by yalh76** [comment]
You can try to install the testing version: `yunohost app install https://github.com/YunoHost-Apps/pleroma_ynh/tree/testing --debug`

**Comment by xaloc33** [comment]
@yalh76 the upgrade run without a problem on my RPI thanks for the work you're the best!!

(since it is a big upgrade and it is a RPI it took about 23min so be aware)

**Comment by yalh76** [comment]
Thanks @xaloc33 
Well during the upgrade, I keep the actual config file, do you think it will be better to regenerate a new one ?

**Comment by xaloc33** [comment]
No I think that keeping the actual one is the best option but my config file got changed. For example all the mrf policies were deleted.

**Comment by yalh76** [comment]
OK then, I will merge the PR.
